#####
# NOTICE OF DEPRECATION
#
# This Docker Image was superseded by the combo bzip2/sra image.
#####

FROM ncbi/sra-tools:latest

# cd sratools

# aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/j5i5h1i5
# sudo docker build --no-cache -t sratools:alpha-0.1 .

# docker tag sratools:alpha-0.1 public.ecr.aws/j5i5h1i5/sratools:alpha-0.1
# docker push public.ecr.aws/j5i5h1i5/sratools:alpha-0.1